attempt at bug fix in ojm.py
Attempt to fix this runtime error:
vsc20170@ln03 [549] ~/data/jobmonitor$ cat ojm.err
Traceback (most recent call last):
File "ojm.py", line 42, in <module>
timestamp = sampler.sample(verbose=verbose)
File "/data/antwerpen/201/vsc20170/jobmonitor/showq.py", line 878, in
sample
overview_line = job.check_for_issues(timestamp)
File "/data/antwerpen/201/vsc20170/jobmonitor/showq.py", line 618, in
check_for_issues
if sample.check_for_issues():
File "/data/antwerpen/201/vsc20170/jobmonitor/showq.py", line 244, in
check_for_issues
self.mhost_job_info  = NeighbouringJobInfo(self)
File "/data/antwerpen/201/vsc20170/jobmonitor/showq.py", line 489, in
__init__
job2sample = job2.get_sample(timestamp)
File "/data/antwerpen/201/vsc20170/jobmonitor/showq.py", line 662, in
get_sample
sample = self.samples[timestamp]
KeyError: '2017.02.14.22h09'
not quite sure what causes the problem. removing folder ‘running’
before restarting fixes the problem